// Generates db/seed.sql from the default content files, so the database starts identical to the site.
// Usage: npm run seed:sql   (idempotent: existing keys are left untouched)
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ctx = { window: {} };
vm.createContext(ctx);
for (const f of ['assets/site-data.js', 'assets/projects-data.js']) {
  vm.runInContext(fs.readFileSync(path.join(__dirname, '..', f), 'utf8'), ctx, { filename: f });
}
const S = ctx.window.DEFAULT_SITE, P = ctx.window.DEFAULT_PROJECTS;
const rows = {
  site: S.site, systems: S.systems, experience: S.experience,
  skills: S.skills, customSections: S.customSections || [], projects: P
};

// Dollar-quoted JSON with a tag that cannot appear in the payload.
const tag = '$pf_seed$';
let out = '-- Generated by scripts/build-seed.js. Do not edit by hand.\n';
for (const [k, v] of Object.entries(rows)) {
  const json = JSON.stringify(v);
  if (json.includes(tag)) throw new Error('seed tag collision in ' + k);
  out += `insert into public.content (key, data) values ('${k}', ${tag}${json}${tag}::jsonb) on conflict (key) do nothing;\n`;
}
process.stdout.write(out);
